# Generated by Django 5.2.5 on 2025-08-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fahrzeug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=255)),
                ('kennzeichen', models.CharField(max_length=20)),
                ('funkrufname', models.CharField(max_length=20)),
                ('standort', models.CharField(max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
            ],
        ),
    ]
