# Generated by Django 5.2.5 on 2025-08-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrzeug',
            name='bemerkung',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Geraeteraum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=255)),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geraeteraeume', to='fahrzeuge.fahrzeug')),
            ],
        ),
    ]
