# Generated by Django 5.2.5 on 2025-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0002_fahrzeug_bemerkung_geraeteraum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geraeteraum',
            name='fahrzeug',
        ),
        migrations.AddField(
            model_name='geraeteraum',
            name='fahrzeuge',
            field=models.ManyToManyField(related_name='geraeteraeume', to='fahrzeuge.fahrzeug'),
        ),
    ]
