# Generated by Django 5.2.5 on 2025-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0003_remove_geraeteraum_fahrzeug_geraeteraum_fahrzeuge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geraeteraum',
            name='fahrzeuge',
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='geraeteraum',
            field=models.ManyToManyField(related_name='geraeteraum', to='fahrzeuge.geraeteraum'),
        ),
    ]
