# Generated by Django 5.2.5 on 2025-09-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0004_remove_geraeteraum_fahrzeuge_fahrzeug_geraeteraum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrzeug',
            name='geraeteraum',
            field=models.ManyToManyField(blank=True, null=True, related_name='geraeteraum', to='fahrzeuge.geraeteraum'),
        ),
    ]
