# Generated by Django 5.2.5 on 2025-09-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0005_alter_fahrzeug_geraeteraum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrzeug',
            name='geraeteraum',
            field=models.ManyToManyField(related_name='geraeteraum', to='fahrzeuge.geraeteraum'),
        ),
    ]
