# Generated by Django 5.2.5 on 2025-09-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0006_alter_fahrzeug_geraeteraum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fahrzeug',
            name='geraeteraum',
        ),
    ]
