# Generated by Django 5.2.5 on 2025-08-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geraete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruefungsart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Checkliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geraete.geraetekategorie')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruefungen.pruefungsart')),
            ],
        ),
        migrations.CreateModel(
            name='Checklistenpunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ist_pflicht', models.BooleanField(default=True)),
                ('checkliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruefungen.checkliste')),
            ],
        ),
        migrations.CreateModel(
            name='Pruefung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('pruefer', models.CharField(max_length=255)),
                ('bestanden', models.BooleanField(default=False)),
                ('bemerkung', models.TextField(blank=True)),
                ('geraet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geraete.geraet')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruefungen.pruefungsart')),
            ],
        ),
        migrations.CreateModel(
            name='Antwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False)),
                ('bemerkung', models.TextField(blank=True)),
                ('punkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruefungen.checklistenpunkt')),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruefungen.pruefung')),
            ],
            options={
                'unique_together': {('pruefung', 'punkt')},
            },
        ),
    ]
