# Generated by Django 5.2.5 on 2025-08-25 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruefungen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistenpunkt',
            name='checkliste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkte', to='pruefungen.checkliste'),
        ),
    ]
