# Generated by Django 5.2.5 on 2025-08-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruefungen', '0002_alter_checklistenpunkt_checkliste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antwort',
            name='pruefung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antworten', to='pruefungen.pruefung'),
        ),
    ]
