# Generated by Django 5.2.5 on 2025-09-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruefungen', '0003_alter_antwort_pruefung'),
        ('pruefungen', '0004_auto_20250901_1617'),
    ]

    operations = [
    ]
