# Generated by Django 5.2.5 on 2025-09-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruefungen', '0005_merge_20250901_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruefung',
            name='bestanden',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
