# Generated by Django 5.2.5 on 2025-09-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruefungen', '0006_alter_pruefung_bestanden'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefungsart',
            name='beschreibung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pruefungsart',
            name='intervall_monate',
            field=models.PositiveIntegerField(blank=True, help_text='Anzahl Monate bis zur nächsten Prüfung (leer lassen, wenn kein Intervall)', null=True),
        ),
    ]
