# Generated by Django 5.2.5 on 2025-09-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0004_alter_geraet_fahrzeug'),
        ('pruefungen', '0007_pruefungsart_beschreibung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefungsart',
            name='geraetekategorie',
            field=models.ManyToManyField(to='geraete.geraetekategorie', verbose_name='kategorie'),
        ),
    ]
