# Generated by Django 5.2.5 on 2025-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruefungen', '0008_pruefungsart_geraetekategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefung',
            name='feueron',
            field=models.BooleanField(default=False),
        ),
    ]
