# Generated by Django 5.2.5 on 2025-09-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruefungen', '0009_pruefung_feueron'),
    ]

    operations = [
        migrations.AddField(
            model_name='antwort',
            name='is_pflicht',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='antwort',
            name='punkt_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antwort',
            name='punkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pruefungen.checklistenpunkt'),
        ),
    ]
