# Generated by Django 5.2.5 on 2025-10-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0005_alter_geraet_status'),
        ('pruefungen', '0010_antwort_is_pflicht_antwort_punkt_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruefungsart',
            name='geraetekategorie',
            field=models.ManyToManyField(blank=True, null=True, to='geraete.geraetekategorie', verbose_name='kategorie'),
        ),
    ]
