# Generated by Django 5.2.5 on 2025-08-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fahrzeuge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geraetekategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geraet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('identifikation', models.CharField(max_length=100, unique=True)),
                ('seriennummer', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bemerkung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahrzeuge.fahrzeug')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geraete.geraetekategorie')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geraete.status')),
            ],
            options={
                'ordering': ['kategorie', 'bezeichnung'],
            },
        ),
    ]
