# Generated by Django 5.2.5 on 2025-08-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0002_fahrzeug_bemerkung_geraeteraum'),
        ('geraete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geraet',
            name='fahrzeug',
        ),
        migrations.AddField(
            model_name='geraet',
            name='geraeteraum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fahrzeuge.geraeteraum'),
        ),
    ]
