# Generated by Django 5.2.5 on 2025-09-01 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0004_remove_geraeteraum_fahrzeuge_fahrzeug_geraeteraum'),
        ('geraete', '0002_remove_geraet_fahrzeug_geraet_geraeteraum'),
    ]

    operations = [
        migrations.AddField(
            model_name='geraet',
            name='fahrzeug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geraete', to='fahrzeuge.fahrzeug'),
        ),
        migrations.AlterField(
            model_name='geraet',
            name='geraeteraum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fahrzeuge.geraeteraum'),
        ),
    ]
