# Generated by Django 5.2.5 on 2025-10-06 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0004_alter_geraet_fahrzeug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geraet',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geraete.status'),
        ),
    ]
