# Generated by Django 5.2.5 on 2025-10-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fahrzeuge', '0007_remove_fahrzeug_geraeteraum'),
        ('geraete', '0005_alter_geraet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wartungsart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('intervall_monate', models.PositiveSmallIntegerField()),
                ('kategorie', models.CharField(choices=[('FAHRZEUG', 'Fahrzeug'), ('GERAET', 'Gerät'), ('BEIDES', 'Gerät und Fahrzeug')], max_length=30)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wartungsart',
                'verbose_name_plural': 'Wartungsarten',
            },
        ),
        migrations.CreateModel(
            name='Wartungszuordnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letzte_wartung', models.DateField(blank=True, null=True)),
                ('naechste_wartung', models.DateField(blank=True, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('fahrzeug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fahrzeuge.fahrzeug')),
                ('geraet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geraete.geraet')),
                ('wartungsart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wartung.wartungsart')),
            ],
        ),
        migrations.CreateModel(
            name='Wartungsvorgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True, help_text='Datum, an dem die Wartung angelegt oder durchgeführt wurde.')),
                ('abschluss_datum', models.DateField(blank=True, help_text='Datum an dem die Wartung abgeschlossen worden ist.', null=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_arbeit', 'In Arbeit'), ('abgeschlossen', 'Abgeschlossen')], default='offen', help_text='Status des Wartungsvorgangs', max_length=20)),
                ('durchgeführt_von', models.CharField(blank=True, help_text='Person die die Wartung durchgeführt hat', max_length=100, null=True)),
                ('bemerkung', models.TextField(blank=True, help_text='Freitextfeld für zusätzliche Hinweise oder Beobachtungen.', null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('fahrzeug_name', models.CharField(blank=True, max_length=150, null=True)),
                ('geraet', models.CharField(blank=True, max_length=150, null=True)),
                ('wartungsart_name', models.CharField(blank=True, max_length=150, null=True)),
                ('zuordnung', models.ForeignKey(blank=True, help_text='Bezieht sich auf eine bestimmte Wartungszuordnung (Fahrzeug/Gerät + Wartungsart).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vorgaenge', to='wartung.wartungszuordnung')),
            ],
        ),
    ]
