# Generated by Django 5.2.5 on 2025-10-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wartungsvorgang',
            old_name='durchgeführt_von',
            new_name='durchgefuehrt_von',
        ),
    ]
