# Generated by Django 5.2.5 on 2025-10-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wartung', '0002_rename_durchgeführt_von_wartungsvorgang_durchgefuehrt_von'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wartungsvorgang',
            old_name='geraet',
            new_name='geraet_name',
        ),
    ]
